[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duct = "0.13"
serde_yaml = "0.9"
probe-rs-target = { git = "https://github.com/probe-rs/probe-rs.git" }
jep106 = "0.2"
